XXX

=over 4

=item $promise = $session->go ($url)

Navigate to the browsing context to a URL (the Go command).

The first argument must be a URL object (L<Web::URL>).

It returns a promise (L<Promise>) that is to be resolved when the
WebDriver command returns (or to be rejected with an error).

=item $session->url->then (sub { $url = shift })

Get the current document URL of the browsing context (the Get Current
URL command).

It returns a promise (L<Promise>) that is to be resolved with a URL
object (L<Web::URL>) when the URL is obtained (or to be rejected with
an error).

=item $session->get_cookie ($name)->then (sub { $cookies = shift })

Get cookies by name.

The first argument must be a character string of the cookie name.

It returns a promise (L<Promise>) that is to be resolved with an array
reference of zero or more hash references representing cookies (or to
be rejected with an error).  A cookie has following name/value pairs:

=over 4

=item name => $string

The cookie name.

=item value => $string

The cookie value.

=item domain => $string

The cookie's domain.

=item path => $string

The cookie's path.

=item secure => $boolean

Whether the cookie has the C<Secure> attribute or not.

=item httponly => $boolean

Whether the cookie has the C<HttpOnly> attribute or not.

=back

=item $promise = $session->set_cookie ($name, $value, $optname => $optvalue, ...)

Set a cookie.

The first argument must be a character string of the cookie name.

The second argument must be a character string of the cookie value.

The remaining arguments are zero or more name/value pairs specifying
following options:

=over 4

=item domain => $string

A character string of the C<Domain> attribute value.

=item path => $string

A character string of the C<Path> attribute value.

=item secure => $boolean

Whether the cookie has the C<Secure> attribute or not.

=item httponly => $boolean

Whether the cookie has the C<HttpOnly> attribute or not.  Note that
ChromeDriver does not support this option at the time of writing.

=item max_age => $delta_seconds

The number of seconds specified in the C<Max-Age> attribute value.

=back

It returns a promise (L<Promise>) that is to be resolved after the
cookie has been set (or to be rejected with an error).

=item $promise = $session->switch_to_frame_by_selector ($selector)

Select a browsing context (the Switch To Frame command).

The first argument must be a character string of the group of
selectors used to select an C<iframe> element.

It returns a promise (L<Promise>) that is to be resolved when a
browsing context is selected (or to be rejected with an error).

=item $session->screenshot ($name => $value, ...)->then (sub { $bytes = shift })

Take a screenshot (the Take Screenshot and Take Element Screenshot
commands).

Zero or more options can be specified as name/value pair arguments.

If the C<selector> option is specified, an element screenshot of the
element selected by the value is taken.  The value must be a character
string of the group of selectors.  Otherwise, a window screenshot is
taken.  If the WebDriver server does not support Take Element
Screenshot command, this option is ignored.

It returns a promise (L<Promise>) that is to be resolved with the byte
string of the screenshot image data (or to be rejected with an error).

=item $session->http_get ($path_segments)->then (sub { $res = shift })

Send a command using the session with the HTTP C<GET> method.

The first argument must be an array reference of path segments.
Segments C<session> and the session ID is prepended before these
segments to construct the request URL.

It returns a promise (L<Promise>) that is to be resolved with a
L<Web::Driver::Client::Response> object containing the response to the
request (or to be rejected with an error).

=item $session->http_post ($path_segments, $params)->then (sub { $res = shift })

Send a command using the session with the HTTP C<POST> method.

The first argument must be an array reference of path segments.
Segments C<session> and the session ID is prepended before these
segments to construct the request URL.

The second argument must be a hash reference that can be used to
create the payload body's JSON data.

It returns a promise (L<Promise>) that is to be resolved with a
L<Web::Driver::Client::Response> object containing the response to the
request (or to be rejected with an error).

=item $session->http_delete ($path_segments)->then (sub { $res = shift })

Send a command using the session with the HTTP C<DELETE> method.

The first argument must be an array reference of path segments.
Segments C<session> and the session ID is prepended before these
segments to construct the request URL.

It returns a promise (L<Promise>) that is to be resolved with a
L<Web::Driver::Client::Response> object containing the response to the
request (or to be rejected with an error).

=item $promise = $session->close

Delete the session from the WebDriver server (the Delete Session
command).

It returns a promise (L<Promise>) that is to be resolved when the
server returns (or to be rejected with an error).

This method must be explicitly invoked when the session is no longer
used.

=back

=head1 SEE ALSO

L<Web::Driver::Connection>.

=head1 SPECIFICATION

WebDriver <https://w3c.github.io/webdriver/webdriver-spec.html>.

=head1 AUTHOR

Wakaba <wakaba@suikawiki.org>

=head1 LICENSE

Copyright 2016-2017 Wakaba <wakaba@suikawiki.org>.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
